### PR TITLE
Rakotoew

### PR DESCRIPTION
**Pull request by rakotoew**

### CODE REVIEW

**Review by Rominos111 — COMMENTED** [review]
`fr.chardonnet_rakotoanosy.soundroulette`

**Review by ythepaut — CHANGES_REQUESTED** [review]
`fr.chardonnet_rakotoanosy.soundroulette.activity` more like `fr.chardonnet.soundroulette.activity`

**Review by Rominos111 — CHANGES_REQUESTED** [review]
Typo : `fr.chardonnet_rakotoanosy.soundroulette`

**Review by LucCha42 — CHANGES_REQUESTED** [review]
Unfinished and unworking mutli-selection.

**Review by LucCha42 — APPROVED** [review]

**Pull request merged**
